### ISSUE TITLE
New useful information

### ISSUE THREAD

**Issue by dangrunger** [dangrunger/vacilometro-bot#5]
If all the conditions are met correctly, the reward is issued instantly.
    To obtain a Galaxy Brain, the following conditions must be met:
    2.1 - Only answers in other people's questions selected by other participants are taken into account
    2.2 - If there are already more than 2 of your answers to your questions, then you will not be able to receive the reward (until you cancel them)
    2.3 - The brain is issued only on the condition that it will be exactly the answer No. 2, and it will meet the requirements of paragraph No. 2.1

**Comment by felipecal** [comment]
'-
